import { fetchValidationChunk } from "./validation-client";

export type CapcutResult = { batchIndex: number; isValid: boolean; message: string; netflixId: string | null; cookiesData: Array<{ domain: string; flag: string; path: string; secure: boolean; expiry: string; name: string; value: string }>; accountInfo: Record<string, any>; netscapeFormat: string };
let controller: AbortController | null = null;
let subscribers = new Set<(event: { type: string; [key: string]: any }) => void>();
let state = { results: [] as CapcutResult[], total: 0, progress: 0, statusMessage: "Pret", running: false };
function notify(event: { type: string; [key: string]: any }) { subscribers.forEach((subscriber) => { try { subscriber(event); } catch {} }); }
export function subscribe(subscriber: (event: { type: string; [key: string]: any }) => void) { subscribers.add(subscriber); subscriber({ type: "snapshot", ...state }); return () => { subscribers.delete(subscriber); }; }
export async function startValidation(cookieText: string) { stopValidation(); controller = new AbortController(); state = { results: [], total: 0, progress: 0, statusMessage: "Validation en cours...", running: true }; notify({ type: "start" }); try { let start = 0; let finished = false; while (!finished && !controller.signal.aborted) { await fetchValidationChunk("/api/capcut", cookieText, start, 20, controller.signal, (event) => { if (event.type === "init") { state.total = event.total || 0; notify(event); } else if (event.type === "result") { state.results.push(event.data); state.progress = event.progress || state.progress; notify(event); } else if (event.type === "done") { start = event.nextStart ?? start + 20; finished = event.finished === true; if (finished) { state.statusMessage = `Termine - ${event.valid} valides, ${event.invalid} invalides`; notify(event); } } }); } } catch (error) { if ((error as Error).name !== "AbortError") notify({ type: "error", message: (error as Error).message }); } state.running = false; controller = null; notify({ type: "stopped" }); }
export function stopValidation() { controller?.abort(); controller = null; if (state.running) { state.running = false; state.statusMessage = "Validation arretee"; notify({ type: "stop" }); } }