#!/usr/bin/env python3
"""Paramount+ Cookie Checker.

Parses a Netscape HTTP Cookie file and tests whether the cookies are valid for
Paramount+ by loading the site with the cookies attached and checking whether a
login redirect occurs.

Usage:
    python paramount_cookie_checker.py path/to/cookies.txt
    python paramount_cookie_checker.py --stdin
    python paramount_cookie_checker.py --sample
"""

from __future__ import annotations

import argparse
import html as htmlmod
import json
import re
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

import requests

try:
    from selenium import webdriver
    from selenium.webdriver.common.by import By
    from selenium.webdriver.support.ui import WebDriverWait
    from selenium.webdriver.support import expected_conditions as EC
    from selenium.common.exceptions import TimeoutException, NoSuchDriverException
    from webdriver_manager.chrome import ChromeDriverManager
    from selenium.webdriver.chrome.service import Service
    SELENIUM_AVAILABLE = True
except ImportError:
    SELENIUM_AVAILABLE = False


SAMPLE_COOKIE_TEXT = '''# Netscape HTTP Cookie File
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
.paramountplus.com	TRUE	/	FALSE	1786853144	sfmc_sub	undefined
.paramountplus.com	TRUE	/	FALSE	1821321494	ab.storage.userId.8cb8412e-2475-416f-b1df-c03199764b1f	%7B%22g%22%3A%22338534209478%22%2C%22c%22%3A1786761494198%2C%22l%22%3A1786761494203%7D
www.paramountplus.com	FALSE	/	FALSE	1786853144	pplus_timezone	Atlantic%2FReykjavik
.paramountplus.com	TRUE	/	FALSE	1786853144	mid	undefined
.paramountplus.com	TRUE	/	FALSE	1786853144	eupubconsent-v2	CQm-o8AQm-o8AAcABBFRCmFgAPLgAELgACiQLesR_C5dbWlj-TZ3abskeYxP1nhi4sAxAgaAkiAFSLKQIAQEx2EQNAyIICACGRIAqhTBIQNkEAAUQUAAIIAFKABMYAyU4BIIIABAgBMBAAJACEACgoggAAAIAgAfBAQgmAqEYdKMWFQAwIgCAkAgIAAAAIAFAQMABAEIZAKAERAEQggAEQgAgAIBAAAAQBgIAAEBAgAAACEABAAAAAQAEAABAAAAEAQAACAAoAAAAAAAAiAAAAAEAACgwEACYKFRBCWBAIEAgIQQIAFBWEABAgCAABICiAABIEBAgBABVYRAAQAgAAAABAACCAAEAAAgACAQAQAEAgAAgACgADAAgAAgAAEAAEAFAAAAAAAKAiAAAAAAAAAQAACCBCAAgEABYUABAACAiACAAgAAAgAAAAAAAAAgAAAAQEACCAAIAAACAAgAAAAAAAAgQAAEAAAAAoAAEAAAAAAAQABAAAAAABAAAAACAAAQAAIBAIAAAAAAAAIAAAAAAAAAAAQAAAAA.flwACFwAAAAA.IMBMR_C5dbWlj-TZ3abskeYxf1nhi4sAxAgaAsiAFSLKQIAQE12EQNEyIICACGRIAqhTBIQNsEAgUQUABIIAFKABsYAyU4BIIIABAgBMBQAJACEACgoggAAAIAgAfBAQgmQqEYdKMWFQAwIgiIkAgIIAAAIAFAQMABAEIZAKAERAEwggCEQgAgAIBAAAAQBgIEAEBAgAAAKEABAAAAAQAEAARAAAAEAQAACAAoAAEAACAQiAAAAAEAACgAAAAAAAAAAE
.paramountplus.com	TRUE	/	FALSE	1821321845	kv_install_sent	1786710211479
.paramountplus.com	TRUE	/	FALSE	1786853144	l	undefined
www.paramountplus.com	FALSE	/	FALSE	1794537857	abtest_api_overrides	%7B%7D
www.paramountplus.com	FALSE	/	FALSE	1809657496	cbsiaa	322833774067
.paramountplus.com	TRUE	/	FALSE	1786853144	ttcsid	1786757508939::F3zkfOk03_zZo0O8XToh.2.1786757518957.0::1.-11056.0::0.0.0.0::0.0.0
#HttpOnly_www.paramountplus.com	FALSE	/	FALSE	1818299499	CBS_RR	US
www.paramountplus.com	FALSE	/	FALSE	1786853144	ptv_device_id	5fc0dd3c-cbc8-4664-b2ce-2cd9bd12fab3
.paramountplus.com	TRUE	/	FALSE	1786853144	_clsk	xzab9a%5E1783464242180%5E1%5E0%5Ea.clarity.ms%2Fcollect
www.paramountplus.com	FALSE	/	FALSE	1818297831	CBS_COM	MTJEMkM0MDY4NjU4QjE4NzA1RTJEOUY0NkZGNzg2RUFGMzVGNzdGM0IyMkU5OTdDMjA1Mjk2RDMxQkE0NDMyQzoxODE4Mjk3ODMxNzAxOjI4ODE5NjI1NTNjMTEyN2Q5NTc0NDAzZjQ3ZWRhYmU5OjMuMDow
www.paramountplus.com	FALSE	/	FALSE	1786853144	ovvuid	76b06cd8-e934-4eb0-b4cf-0f03eb1556e0
www.paramountplus.com	FALSE	/	FALSE	1786849899	WcoSMza	63ea216c4bc34a45a7c788ff30fbaaad.84c9f3b6fd0873e1bb1b4b58bcdade061aaee07f34c312d4898279e8e06403c52c0f6321f4acd45b52091a4b89a15f2dc8a3a7a530a739ccce7709ba0d4240d556d553f6595f57554e27ba853d2a61d26d3fb6ca5068c1c30032a8b48c4c2367e93b625894169173bb0471402e47047e8993e3fd4ceedc8195f08a97e0e7f6fc39e314295884506beb6861493cb554dbe4515efb14d6ac35eea2ccdba5ee12f4f042064e524b4ced9276361aab073ada11f0bfe79f0465af7c1fcceefb3cad2d7bdc6ad9d05f72bcafff5de11bf5c1f85b2374ec3999e52a7b91aad8502830ccf8.0x615cd7ddc0e5514891b864619cf438a8e0abc95b7281d06430b13e2e2c9070fe
.paramountplus.com	TRUE	/	FALSE	1791233814	_gcl_aw	GCL.1783457814.EAIaIQobChMI5sXq_bnBlQMVJZWDBx2dchOCEAAYASAEEgJ9zvD_BwE
.paramountplus.com	TRUE	/	FALSE	1786853144	s_sq	%5B%5BB%5D%5D
.paramountplus.com	TRUE	/	FALSE	1786769999	first_page_today	false
.paramountplus.com	TRUE	/	FALSE	1786853144	u	undefined
www.paramountplus.com	FALSE	/	FALSE	1786767105	tn_vw	668
.paramountplus.com	TRUE	/	FALSE	1786853144	OptanonAlertBoxClosed	2026-07-07T20:56:47.382Z
.paramountplus.com	TRUE	/	FALSE	1786853144	prevPageType	account
www.paramountplus.com	FALSE	/	FALSE	1786853144	pin_switch	0
.paramountplus.com	TRUE	/	TRUE	1794539516	_rdt_uuid	1783457815919.4f109566-1acc-4e43-a028-f439bb603c8a
.paramountplus.com	TRUE	/	FALSE	1821323516	kv_id	kw5ed6f9761ad7a
.paramountplus.com	TRUE	/	FALSE	1821323508	ab.storage.sessionId.8cb8412e-2475-416f-b1df-c03199764b1f	%7B%22g%22%3A%2215ecfcbf-393a-f81d-8366-35f53b7faf9d%22%2C%22e%22%3A1786765308553%2C%22c%22%3A1786761494200%2C%22l%22%3A1786763508553%7D
.paramountplus.com	TRUE	/	FALSE	1818299512	OptanonConsent	isGpcEnabled=0&datestamp=Sat+Aug+15+2026+03%3A11%3A52+GMT%2B0000+(heure+moyenne+de+Greenwich)&version=202601.2.0&browserGpcFlag=0&isIABGlobal=false&identifierType=Cookie+Unique+Id&hosts=&genVendors=V20%3A0%2CV16%3A0%2CV21%3A0%2C&landingPath=NotLandingPage&groups=1%3A1%2C2%3A1%2C3%3A1%2C4%3A1%2C5%3A1&geolocation=FR%3BPAC&AwaitingReconsent=false&consentId=df2320eb2bd6ba6d379d0520b37601b869d14722b310a6a48c401de8c6aca534&isAnonUser=0
.paramountplus.com	TRUE	/	FALSE	1786853144	_tt_enable_cookie	1
.paramountplus.com	TRUE	/	FALSE	1786853144	_gcl_gs	2.1.k1$i1783457792$u141367091
.paramountplus.com	TRUE	/	FALSE	1786853144	j	undefined
.paramountplus.com	TRUE	/	TRUE	1786853144	__pxvid	645df901-7a46-11f1-a6f0-9ea33ff746f8
.paramountplus.com	TRUE	/	FALSE	1786853144	_clck	xb2ex5%5E2%5Eg7j%5E1%5E2379
.paramountplus.com	TRUE	/	FALSE	1794539516	_fbp	fb.1.1783457817444.465032320722432754
.paramountplus.com	TRUE	/	FALSE	1791233809	_gcl_au	1.1.323029398.1783457809.57007924.1783457822.1783457821
.paramountplus.com	TRUE	/	FALSE	1791233814	_gcl_dc	GCL.1783457814.EAIaIQobChMI5sXq_bnBlQMVJZWDBx2dchOCEAAYASAEEgJ9zvD_BwE
.paramountplus.com	TRUE	/	FALSE	1818299515	_pin_unauth	dWlkPU0yRXlNR013WXprdE9EWXpZeTAwTjJVNExXRmtObVV0TVdRNE5HRmpaRGM0WXpGbA
www.paramountplus.com	FALSE	/	TRUE	1786853144	_pxvid	63f201af-7a46-11f1-a5bf-d2a66eed7e49
.paramountplus.com	TRUE	/	FALSE	1786853144	_scid	Wrv1g8k8gW388c9lEFt5_nLAsRvZdb0E
.paramountplus.com	TRUE	/	FALSE	1786853144	_scid_r	Wrv1g8k8gW388c9lEFt5_nLAsRvZdb0E
.paramountplus.com	TRUE	/	TRUE	1820459517	_scor_uid	4e9238dedba24f36b237b86ba59e326f
.paramountplus.com	TRUE	/	FALSE	1786853144	_sctr	1%7C1786752000000
.paramountplus.com	TRUE	/	FALSE	1786853144	_ttp	01KWZ5X7ANMTKKJB4VG0FC23XQ_.tt.1
.paramountplus.com	TRUE	/	TRUE	1786853144	_twpid	tw.1783457815787.79722410494478353
.paramountplus.com	TRUE	/	FALSE	1786849915	_uetsid	158dc2a0984911f1b1e96d94f40103b3
.paramountplus.com	TRUE	/	FALSE	1820459515	_uetvid	64375fc07a4611f1a595e598a1f164c8
www.paramountplus.com	FALSE	/	FALSE	1786853144	aa-abandon-ovl	%2F
.paramountplus.com	TRUE	/	FALSE	1821321494	ab.storage.deviceId.8cb8412e-2475-416f-b1df-c03199764b1f	%7B%22g%22%3A%2292241600-ac3c-0857-1884-76f506ea7654%22%2C%22c%22%3A1786757577323%2C%22l%22%3A1786761494201%7D
.paramountplus.com	TRUE	/	FALSE	1821321499	AMCV_10D31225525FF5790A490D4D%40AdobeOrg	1585540135%7CMCMID%7C04826504935064546611247388734160595612%7CMCAAMLH-1787366299%7C7%7CMCAAMB-1787366299%7C6G1ynYcLPuiQxYZrsz_pkqfLG9yMXBpb2zX5dvJdYQJzPXImdj0y%7CMCOPTOUT-1786768699s%7CNONE%7CvVersion%7C4.4.0%7CMCCIDH%7C-1212232576
.paramountplus.com	TRUE	/	FALSE	1786853144	AMCVS_10D31225525FF5790A490D4D%40AdobeOrg	1
.paramountplus.com	TRUE	/	FALSE	1786853144	CBS_ADV_SUBSES_VAL	4
.paramountplus.com	TRUE	/	FALSE	1786853144	CBS_ADV_VAL	b
www.paramountplus.com	FALSE	/	FALSE	1787368308	CBS_ATTB	sl:f|ts:2026-08-15T03:11:48.568Z
www.paramountplus.com	FALSE	/	FALSE	1786853144	CBS_DEVICEID	04826504935064546611247388734160595612
www.paramountplus.com	FALSE	/	FALSE	1786853144	CBS_PID	4051e532-9ee1-4c11-9186-8db444df569c
#HttpOnly_www.paramountplus.com	FALSE	/	FALSE	1818299499	CBS_ST	SUBSCRIBER
www.paramountplus.com	FALSE	/	FALSE	1818297492	CBS_U	ge:0|gr:8
www.paramountplus.com	FALSE	/	FALSE	1786847770	dmaInfo	528
.paramountplus.com	TRUE	/	FALSE	1786853144	ET_CID	undefined
www.paramountplus.com	FALSE	/	FALSE	1786799506	graph	%7B%22svod%22%3A%22WyJmLXNpZ25pbiIsImh0dHBzOlwvXC93d3cucGFyYW1vdW50cGx1cy5jb21cLyIsbnVsbCwyLG51bGwsbnVsbF0%3D%22%2C%22cookieExpiration%22%3A1786799505%2C%22cookiePath%22%3A%22%5C%2F%22%7D
.paramountplus.com	TRUE	/	TRUE	1786853144	IR_3065	1786763515354%7C0%7C1786763515354%7C%7C
.paramountplus.com	TRUE	/	FALSE	1786853144	IR_gbd	paramountplus.com
.paramountplus.com	TRUE	/	FALSE	1786853144	jb	undefined
.paramountplus.com	TRUE	/	TRUE	1786853144	kndctr_10D31225525FF5790A490D4D_AdobeOrg_identity	CiYwNDgyNjUwNDkzNTA2NDU0NjYxMTI0NzM4ODczNDE2MDU5NTYxMlIRCPqR%2DvLzMxgBKgRJUkwxMAPwAaPTr5iANA%3D%3D
www.paramountplus.com	FALSE	/	FALSE	1786853144	optanonConsentValues	{"kidsFlag":"true","_optanonConsentPerformance":"1","_optanonConsentFunctional":"1","_optanonConsentMarketing":"1","_optanonConsentSocial":"1"}
.paramountplus.com	TRUE	/	FALSE	1786853144	OTAdditionalConsentString	2~55.70.89.144.149.196.230.327.494.495.540.864.1031.1097.1230.1301.1312.1415.1512.1548.1570.1716.1859.1942.2072.2133.2279.2343.2498.2577.2739.2822.3235.3330.16831.27831~dv
www.paramountplus.com	FALSE	/	TRUE	1786853144	pxcts	arVpxNi3zpcY3qiHDaZYSCQm2yVzMWVkBVbtMRVPuY0=:Kr6HkldH5I-x2rJmiAUtPuSEyz5r4NYyFm9AJxHmRXGqQlBxbfrnwttLEL2FhQP3kImytad5QWnx2YSb51bipjLYmfyb3kvO6JqOnwMPFZSi-XugUmAbWSkzb7GcpUBAh8Y62PGGc39H8NoOauAwo7/9AYqisPQcuvLei3nzsssuDJ/7/nsil2oF514xuDHA
.paramountplus.com	TRUE	/	FALSE	1786853144	s_cc	true
.paramountplus.com	TRUE	/	FALSE	1786853144	ttcsid_CD7S5CRC77U9FFTD03T0	1783457815896::xq-T8wjnmHzDOldxD1vN.1.1783457825918.1
.paramountplus.com	TRUE	/	FALSE	1786853144	ttcsid_CJAGL9RC77U0073JQUJ0	1786757508939::dmJj3LXm_xUwDUOPRYem.1.1786757518959.1
.paramountplus.com	TRUE	/	FALSE	1818299513	utag_main	v_id:019f3e5e80bf003a8c698bf6ca140505000a900d00978$_sn:3$_se:45$_ss:0$_st:1786765313689$vapi_domain:paramountplus.com$ses_id:1786761372167%3Bexp-session$_pn:7%3Bexp-session$_prevpage:%2Faccount%2F%3Bexp-1786767113884
'''


def parse_netscape_cookie_file(raw_text: str) -> List[Dict[str, Any]]:
    """Parse a Netscape cookie file and return structured cookie dicts."""
    cookies: List[Dict[str, Any]] = []
    for line in raw_text.splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        parts = [p.strip() for p in line.split('\t')]
        if len(parts) < 7:
            continue

        domain, flag, path, secure, expiry, name, value = parts[:7]
        cookies.append(
            {
                'domain': domain,
                'flag': flag,
                'path': path,
                'secure': secure.upper() == 'TRUE',
                'expiry': expiry,
                'name': name,
                'value': value,
            }
        )
    return cookies


def normalize_domain(domain: str) -> str:
    if not domain:
        return ''
    return domain.lower().lstrip('.')


def is_paramount_domain(domain: str) -> bool:
    d = normalize_domain(domain)
    return d in {'paramountplus.com', 'www.paramountplus.com'} or d.endswith('.paramountplus.com')


def choose_relevant_cookies(cookies: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    relevant: List[Dict[str, Any]] = []
    for cookie in cookies:
        domain = cookie.get('domain', '')
        if is_paramount_domain(domain):
            relevant.append(cookie)
    return relevant


def build_session_with_cookies(cookies: List[Dict[str, Any]]) -> requests.Session:
    session = requests.Session()
    session.headers.update(
        {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0 Safari/537.36',
            'Accept-Language': 'en-US,en;q=0.9',
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
        }
    )

    for cookie in cookies:
        name = cookie.get('name', '')
        value = cookie.get('value', '')
        domain = cookie.get('domain', '')
        path = cookie.get('path', '/')
        if not name or not value:
            continue
        host = normalize_domain(domain)
        if not host:
            continue
        try:
            session.cookies.set(name, value, domain=host, path=path)
        except Exception:
            pass

    return session


def detect_login_page(url: str, html: str) -> bool:
    lower_url = url.lower()
    lower_html = html.lower()
    if 'signin' in lower_url or 'login' in lower_url:
        return True
    if 'sign in' in lower_html or 'log in' in lower_html or 'login' in lower_html:
        return True
    if 'watchlist' in lower_html and 'signin' in lower_html:
        return True
    return False


def extract_profiles_from_html(html: str) -> List[str]:
    names: List[str] = []
    if not html:
        return names

    account_profiles_match = re.search(r'"accountProfiles"\s*:\s*(\[.*?\])\s*(?:,\s*"[A-Za-z0-9_]+"|\s*\})', html, flags=re.S)
    if not account_profiles_match:
        # fallback: look for all "name" occurrences in the page and keep the profile-like ones
        for match in re.finditer(r'"name"\s*:\s*"((?:\\.|[^"\\])*)"', html):
            name = match.group(1).encode('utf-8').decode('unicode_escape')
            if name and name not in names and len(name) < 80:
                names.append(name)
        return names

    profiles_blob = account_profiles_match.group(1)
    for match in re.finditer(r'"name"\s*:\s*"((?:\\.|[^"\\])*)"', profiles_blob):
        name = match.group(1).encode('utf-8').decode('unicode_escape')
        if name and name not in names and len(name) < 80:
            names.append(name)

    return names


def extract_account_details_from_html(html: str) -> Dict[str, Any]:
    details: Dict[str, Any] = {
        'Paramount+ Plan': None,
        'Price': None,
        'Next Billing Date': None,
        'Payment Method': None,
    }

    if not html:
        return details

    def clean_text(value: str) -> str:
        value = htmlmod.unescape(value)
        value = value.replace('&nbsp;', ' ')
        value = re.sub(r'<.*?>', ' ', value, flags=re.S)
        value = re.sub(r'\s+', ' ', value)
        return value.strip()

    label_map = [
        ('Paramount+ Plan', 'Paramount+ Plan'),
        ('Price', 'Price'),
        ('Next Billing Date', 'Next Billing Date'),
        ('Payment Method', 'Payment Method'),
    ]

    # If the page does not clearly contain the actual account section, we do not invent values.
    found_any_label = False
    for label_text, _ in label_map:
        if label_text.lower() in html.lower():
            found_any_label = True
            break
    if not found_any_label:
        return details

    for label_text, output_key in label_map:
        label_pattern = re.compile(rf'(?is)<(?:label|div|span)[^>]*>\s*{re.escape(label_text)}\s*</(?:label|div|span)>')
        if not label_pattern.search(html):
            continue

        # find the value right after the label in the same row, excluding action buttons.
        row_pattern = re.compile(
            rf'(?is){re.escape(label_text)}\s*</(?:label|div|span)>\s*(?:<[^>]+>\s*)*(?:<div|<span|<p|<strong|<b)[^>]*>\s*(.*?)\s*(?:</(?:div|span|p|strong|b)>|<button|$)'
        )
        match = row_pattern.search(html)
        if not match:
            continue
        value = clean_text(match.group(1))
        if value and not any(keyword in value.lower() for keyword in ['edit plan', 'edit payment', 'switch to annual', 'redeem', 'save', 'gift card', 'coupon']):
            details[output_key] = value

    return details


def get_account_details_with_fallback(session: requests.Session) -> Dict[str, Any]:
    urls = [
        'https://www.paramountplus.com/account/',
        'https://www.paramountplus.com/account',
        'https://www.paramountplus.com/api/accounts/current/',
        'https://www.paramountplus.com/api/user/account/',
        'https://www.paramountplus.com/home/',
        'https://www.paramountplus.com/',
    ]

    for url in urls:
        try:
            headers = {}
            if '/account' in url:
                headers['Referer'] = 'https://www.paramountplus.com/user-profile/whos-watching/'
            
            account_response = session.get(url, timeout=20, allow_redirects=True, headers=headers)
            account_html = account_response.text
            
            # Skip cache errors
            if account_response.status_code == 403 and 'Varnish' in account_response.text:
                continue
            
            parsed = extract_account_details_from_html(account_html)
            if any(value is not None and str(value).strip() for value in parsed.values()):
                return parsed
        except (requests.RequestException, ValueError):
            continue

    return {
        'Paramount+ Plan': None,
        'Price': None,
        'Next Billing Date': None,
        'Payment Method': None,
    }


def log_debug(message: str) -> None:
    print(message, file=sys.stderr)


def get_account_details_via_selenium(cookies: List[Dict[str, Any]]) -> Optional[Dict[str, Any]]:
    """Load /account page via Selenium browser to bypass Varnish cache."""
    if not SELENIUM_AVAILABLE:
        log_debug("[LOG] Selenium non disponible, abandon du rendu via navigateur")
        return None
    
    try:
        log_debug("[LOG] Tentative de rendu de /account via Selenium...")
        
        # Initialiser le driver Chrome avec options headless
        options = webdriver.ChromeOptions()
        options.add_argument('--headless')
        options.add_argument('--no-sandbox')
        options.add_argument('--disable-dev-shm-usage')
        options.add_argument('--disable-blink-features=AutomationControlled')
        options.add_argument('user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36')
        
        # Utiliser webdriver-manager pour gérer le driver
        service = Service(ChromeDriverManager().install())
        driver = webdriver.Chrome(service=service, options=options)
        
        try:
            # Charger la page d'accueil d'abord pour définir les cookies
            driver.get('https://www.paramountplus.com/')
            time.sleep(2)
            
            # Ajouter les cookies au navigateur
            for cookie in cookies:
                domain = cookie.get('domain', '').lstrip('.')
                name = cookie.get('name', '')
                value = cookie.get('value', '')
                if not name or not value:
                    continue
                try:
                    driver.add_cookie({
                        'name': name,
                        'value': value,
                        'domain': domain if domain else 'www.paramountplus.com',
                        'path': cookie.get('path', '/'),
                    })
                except Exception as e:
                    log_debug(f"[LOG] Erreur ajout cookie {name}: {e}")
                    pass
            
            log_debug("[LOG] Cookies injectés dans le navigateur")
            time.sleep(1)
            
            # Naviguer vers /account
            account_url = 'https://www.paramountplus.com/account/'
            log_debug(f"[LOG] Navigation via Selenium vers: {account_url}")
            driver.get(account_url)
            
            # Attendre le chargement de la page
            WebDriverWait(driver, 10).until(EC.presence_of_all_elements_located((By.TAG_NAME, 'body')))
            time.sleep(2)
            
            account_html = driver.page_source
            log_debug(f"[LOG] Rendu /account via Selenium réussi: {len(account_html)} caractères")
            
            # Ne pas écrire de fichier HTML de débogage.
            
            # Extraire les données
            parsed_account = extract_account_details_from_html(account_html)
            has_data = any(value is not None and str(value).strip() for value in parsed_account.values())
            
            if has_data:
                log_debug(f"[LOG] Données account trouvées via Selenium: {parsed_account}")
                return parsed_account
            else:
                log_debug("[LOG] Pas de données account dans le rendu Selenium")
                return None
                
        finally:
            driver.quit()
            
    except NoSuchDriverException:
        log_debug("[LOG] WebDriver ChromeDriver non trouvé, abandon du rendu Selenium")
        return None
    except TimeoutException:
        log_debug("[LOG] Timeout lors du rendu Selenium")
        return None
    except Exception as e:
        log_debug(f"[LOG] Erreur lors du rendu Selenium: {type(e).__name__}: {e}")
        return None


def check_paramount_cookies(cookies: List[Dict[str, Any]]) -> Dict[str, Any]:
    relevant = choose_relevant_cookies(cookies)
    result: Dict[str, Any] = {
        'total_cookies': len(cookies),
        'relevant_cookies': len(relevant),
        'is_valid': False,
        'status': 'unknown',
        'message': '',
        'cookies': relevant,
        'checks': {},
        'profile_count': 0,
        'profile_names': [],
        'account_details': {
            'Paramount+ Plan': None,
            'Price': None,
            'Next Billing Date': None,
            'Payment Method': None,
        },
    }

    if not relevant:
        result['message'] = 'Aucun cookie Paramount+ valide trouvé dans le fichier.'
        result['status'] = 'invalid'
        return result

    session = build_session_with_cookies(relevant)
    
    # DEBUG: Afficher les cookies dans la session
    log_debug(f"\n[DEBUG] Cookies dans la session: {len(session.cookies)}")
    for cookie in session.cookies:
        log_debug(f"  - {cookie.name} = {cookie.value[:50]}..." if len(str(cookie.value)) > 50 else f"  - {cookie.name} = {cookie.value}")
    
    urls_to_test = [
        'https://www.paramountplus.com/',
        'https://www.paramountplus.com/account',
        'https://www.paramountplus.com/shows',
    ]

    for url in urls_to_test:
        try:
            r = session.get(url, timeout=15, allow_redirects=True)
            html = r.text[:4000]
            final_url = r.url.lower()
            is_login = detect_login_page(r.url, html)

            result['checks'][url] = {
                'status_code': r.status_code,
                'final_url': r.url,
                'login_like': is_login,
                'contains_watchlist': 'watchlist' in html.lower(),
            }

            if '/home' in final_url:
                profiles_url = 'https://www.paramountplus.com/user-profile/whos-watching/'
                try:
                    log_debug(f"[LOG] navigation vers profil: {profiles_url}")
                    profile_response = session.get(profiles_url, timeout=15, allow_redirects=True)
                    log_debug(f"[LOG] navigation vers profil reussie: status={profile_response.status_code}, url={profile_response.url}")
                    profile_html = profile_response.text
                    if profile_response.status_code == 200 and profile_html:
                        pass
                    profile_names = extract_profiles_from_html(profile_html)
                    log_debug(f"[LOG] recuperation des noms: {'OK' if profile_names else 'FAIL'} -> {profile_names}")
                    result['profile_count'] = len(profile_names)
                    result['profile_names'] = profile_names
                    result['profile_page_url'] = profile_response.url

                    account_url = 'https://www.paramountplus.com/account/'
                    log_debug(f"[LOG] navigation vers account: {account_url}")
                    # DEBUG: Vérifier les cookies de session avant la requête account
                    log_debug(f"[DEBUG] Cookies pour /account: {len(session.cookies)}")
                    cbs_st = session.cookies.get('CBS_ST')
                    log_debug(f"[DEBUG] CBS_ST cookie présent: {cbs_st is not None}")
                    
                    # Ajouter un délai et un referrer pour éviter le cache Varnish
                    time.sleep(1)
                    headers = {
                        'Referer': 'https://www.paramountplus.com/user-profile/whos-watching/',
                        'X-Requested-With': 'XMLHttpRequest',
                    }
                    account_response = session.get(account_url, timeout=20, allow_redirects=True, headers=headers)
                    account_html = account_response.text
                    
                    # DEBUG: En cas de 403, afficher la réponse
                    if account_response.status_code == 403:
                        log_debug(f"[DEBUG] 403 - Réponse partielle: {account_html[:500]}")
                    
                    parsed_account = extract_account_details_from_html(account_html)
                    has_account_data = any(value is not None and str(value).strip() for value in parsed_account.values())

                    log_debug(f"[LOG] navigation vers account reussie: status={account_response.status_code}, url={account_response.url}")
                    log_debug(f"[LOG] recuperation des infos account: {'OK' if has_account_data else 'FAIL'} -> {parsed_account}")

                    if account_response.status_code == 200 and account_html:
                        pass

                    if has_account_data:
                        result['account_details'] = parsed_account
                    else:
                        # Essayer Selenium si la requête directe a échoué
                        if account_response.status_code == 403:
                            log_debug('[LOG] Tentative de contournement du cache Varnish avec Selenium...')
                            selenium_result = get_account_details_via_selenium(relevant)
                            if selenium_result and any(value is not None and str(value).strip() for value in selenium_result.values()):
                                result['account_details'] = selenium_result
                                has_account_data = True
                        
                        if not has_account_data:
                            log_debug('[LOG] fallback account details via get_account_details_with_fallback')
                            result['account_details'] = get_account_details_with_fallback(session)
                            log_debug(f"[LOG] fallback account details: {result['account_details']}")

                    if profile_names:
                        result['is_valid'] = True
                        result['status'] = 'valid'
                        result['message'] = f'Les cookies sont valides. {len(profile_names)} profil(s) trouvé(s): {", ".join(profile_names)}'
                        return result
                except requests.RequestException as exc:
                    log_debug(f"[LOG] erreur navigation/recup: {exc}")
                    pass

            if '/account' in final_url:
                account_details = extract_account_details_from_html(r.text)
                result['account_details'] = account_details

            # Règle métier : tant qu'on n'est pas sur /home, la session n'est pas validée.
            if '/home' not in final_url:
                result['status'] = 'invalid'
                result['message'] = 'Session Paramount+ invalide : aucun /home détecté dans l’URL finale.'
                return result

            if r.status_code in (200, 302, 301) and not is_login:
                result['account_details'] = get_account_details_with_fallback(session)
                result['is_valid'] = True
                result['status'] = 'valid'
                result['message'] = 'Les cookies semblent valides pour Paramount+.'
                return result
        except requests.RequestException as exc:
            result['checks'][url] = {'error': str(exc)}

    result['status'] = 'invalid'
    result['message'] = 'Les cookies ne semblent pas être une session Paramount+ valide.'
    return result


def main() -> int:
    raw_stdin = sys.stdin.read()
    if raw_stdin.strip().startswith('{'):
        try:
            payload = json.loads(raw_stdin)
            cookies = payload.get('cookies', [])
            if isinstance(cookies, list):
                result = check_paramount_cookies(cookies)
                sys.stdout.write(json.dumps(result, ensure_ascii=False))
                return 0 if result['is_valid'] else 1
        except Exception:
            pass

    parser = argparse.ArgumentParser(description='Vérifie des cookies Paramount+ au format Netscape.')
    parser.add_argument('file', nargs='?', help='Fichier .txt contenant les cookies')
    parser.add_argument('--stdin', action='store_true', help='Lire les cookies depuis stdin')
    parser.add_argument('--sample', action='store_true', help='Utiliser un cookie d’exemple')
    args = parser.parse_args()

    if args.sample:
        raw_text = SAMPLE_COOKIE_TEXT
    elif args.stdin:
        raw_text = raw_stdin
    elif args.file:
        path = Path(args.file)
        if not path.exists():
            print(f'Fichier introuvable : {args.file}', file=sys.stderr)
            return 2
        raw_text = path.read_text(encoding='utf-8', errors='ignore')
    else:
        print('Aucune entrée fournie. Utilisez un fichier, --stdin ou --sample.', file=sys.stderr)
        return 2

    cookies = parse_netscape_cookie_file(raw_text)
    result = check_paramount_cookies(cookies)

    print(f"Cookies lus: {result['total_cookies']}")
    print(f"Cookies Paramount+: {result['relevant_cookies']}")
    print(f"Statut: {result['status']}")
    print(f"Message: {result['message']}")

    if result['is_valid']:
        print('[OK] Cookie Paramount+ probablement valide.')
    else:
        print('[FAIL] Cookie Paramount+ probablement invalide ou incomplet.')

    return 0 if result['is_valid'] else 1


if __name__ == '__main__':
    raise SystemExit(main())
