import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("results", "routes/results.tsx"),
  route("directlogin", "routes/directlogin.tsx"),
  route("spotify", "routes/spotify.tsx"),
  route("prime", "routes/prime.tsx"),
  route("crunchyroll", "routes/crunchyroll.tsx"),
  route("paramount", "routes/paramount.tsx"),
  route("capcut", "routes/capcut.tsx"),
  route("perplexity", "routes/perplexity.tsx"),
  route("scribd", "routes/scribd.tsx"),
  route("api/spotify", "routes/api.spotify.ts"),
  route("api/prime", "routes/api.prime.ts"),
  route("api/crunchyroll", "routes/api.crunchyroll.ts"),
  route("api/paramount", "routes/api.paramount.ts"),
  route("api/capcut", "routes/api.capcut.ts"),
  route("api/perplexity", "routes/api.perplexity.ts"),
  route("api/scribd", "routes/api.scribd.ts"),
  route("api/validate", "routes/api.validate.ts"),
  route("api/storage/list", "routes/api-storage-list.ts"),
  route("api/storage/content", "routes/api-storage-content.ts"),
  route("api/storage/url", "routes/api-storage-url.ts"),
  route("api/storage/upload", "routes/api-storage-upload.ts"),
  route("api/db/save", "routes/api-db-save.ts"),
  route("api/directlogin", "routes/api.directlogin.ts"),
] satisfies RouteConfig;
